dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: 98c672f2-99cb-4d75-a7bc-a73fd5872c99
  app: ds-burger-server
  on:
    branch: master