language: java
jdk:
  - openjdk8
script: ./mvnw clean install
#deploy:
#  provider: heroku
#  api_key: $HEROKU_SECURE_KEY
#  app: ds-burger-server
#  on:
#    branch: master
notifications:
  email: daniel.smanioto@gmail.com
